name: XeonSocketBukkit
version: ${project.version}.b${build.number}
description: Communication plugin mask
authors: [Kekshaus]
main: de.nlinz.xeonSocketBukkit.mask.XeonSocketBukkitMask
load: POSTWORLD
